# Don't change this config!

# Use vagrantconfig_local.yaml to override these settings instead.

db_password: secure
db_username: commercedev@localhost 
repository: svn
svn_username: false
svn_password: false
